2017-06-20 11:35:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "?"; SQL statement:
select infoexecut0_.Id as Id1_0_, infoexecut0_.ExecutionIdentifier as Executio2_0_, infoexecut0_.PipelineIdentifier as Pipeline3_0_, infoexecut0_.Repersitory as Repersit4_0_, infoexecut0_.StartDate as StartDat5_0_, infoexecut0_.Status as Status6_0_ from InfoExecution infoexecut0_ where ?-infoexecut0_.StartDate>? [50004-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.value.DataType.getDataType(DataType.java:801)
	at org.h2.expression.Operation.optimize(Operation.java:310)
	at org.h2.expression.Comparison.optimize(Comparison.java:178)
	at org.h2.command.dml.Select.prepare(Select.java:842)
	at org.h2.command.Parser.prepareCommand(Parser.java:262)
	at org.h2.engine.Session.prepareLocal(Session.java:573)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:162)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:160)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1884)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1861)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1838)
	at org.hibernate.loader.Loader.doQuery(Loader.java:909)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
	at org.hibernate.loader.Loader.doList(Loader.java:2551)
	at org.hibernate.loader.Loader.doList(Loader.java:2537)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2367)
	at org.hibernate.loader.Loader.list(Loader.java:2362)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:496)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:229)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1260)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
	at fr.insalyon.creatis.vip.cli.dao.InfoExecutionDAO.deleteExecution(InfoExecutionDAO.java:59)
	at fr.insalyon.creatis.vip.cli.control.Controller.main(Controller.java:88)
2017-06-20 11:36:17 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "?"; SQL statement:
select infoexecut0_.Id as Id1_0_, infoexecut0_.ExecutionIdentifier as Executio2_0_, infoexecut0_.PipelineIdentifier as Pipeline3_0_, infoexecut0_.Repersitory as Repersit4_0_, infoexecut0_.StartDate as StartDat5_0_, infoexecut0_.Status as Status6_0_ from InfoExecution infoexecut0_ where ?-infoexecut0_.StartDate>? [50004-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.value.DataType.getDataType(DataType.java:801)
	at org.h2.expression.Operation.optimize(Operation.java:310)
	at org.h2.expression.Comparison.optimize(Comparison.java:178)
	at org.h2.command.dml.Select.prepare(Select.java:842)
	at org.h2.command.Parser.prepareCommand(Parser.java:262)
	at org.h2.engine.Session.prepareLocal(Session.java:573)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:162)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:160)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1884)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1861)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1838)
	at org.hibernate.loader.Loader.doQuery(Loader.java:909)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
	at org.hibernate.loader.Loader.doList(Loader.java:2551)
	at org.hibernate.loader.Loader.doList(Loader.java:2537)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2367)
	at org.hibernate.loader.Loader.list(Loader.java:2362)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:496)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:229)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1260)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
	at fr.insalyon.creatis.vip.cli.dao.InfoExecutionDAO.deleteExecution(InfoExecutionDAO.java:59)
	at fr.insalyon.creatis.vip.cli.control.Controller.main(Controller.java:88)
2017-06-20 14:05:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-20 14:05:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Unknown data type: "?"; SQL statement:
select infoexecut0_.Id as Id1_0_, infoexecut0_.ExecutionIdentifier as Executio2_0_, infoexecut0_.PipelineIdentifier as Pipeline3_0_, infoexecut0_.Repersitory as Repersit4_0_, infoexecut0_.StartDate as StartDat5_0_, infoexecut0_.Status as Status6_0_ from InfoExecution infoexecut0_ where ?-infoexecut0_.StartDate>? [50004-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.value.DataType.getDataType(DataType.java:801)
	at org.h2.expression.Operation.optimize(Operation.java:310)
	at org.h2.expression.Comparison.optimize(Comparison.java:178)
	at org.h2.command.dml.Select.prepare(Select.java:842)
	at org.h2.command.Parser.prepareCommand(Parser.java:262)
	at org.h2.engine.Session.prepareLocal(Session.java:573)
	at org.h2.engine.Session.prepareCommand(Session.java:514)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:73)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:162)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:186)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:160)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1884)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1861)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1838)
	at org.hibernate.loader.Loader.doQuery(Loader.java:909)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:354)
	at org.hibernate.loader.Loader.doList(Loader.java:2551)
	at org.hibernate.loader.Loader.doList(Loader.java:2537)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2367)
	at org.hibernate.loader.Loader.list(Loader.java:2362)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:496)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:387)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:229)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1260)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103)
	at fr.insalyon.creatis.vip.cli.dao.InfoExecutionDAO.deleteExecution(InfoExecutionDAO.java:59)
	at fr.insalyon.creatis.vip.cli.control.Controller.main(Controller.java:88)
2017-06-20 14:07:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-20 14:13:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INFOEXECUTION[*]"; expected "INSERT, {"; SQL statement:
INFOEXECUTION [42001-190]
2017-06-20 14:16:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM INFOEXECUTION 
INSERT INTO[*] INFOEXECUTION (1,'test','test','test','2015-01-01','running')"; SQL statement:
SELECT * FROM INFOEXECUTION 
INSERT INTO INFOEXECUTION (1,'test','test','test','2015-01-01','running') [42000-190]
2017-06-20 14:16:33 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM INFOEXECUTION 
INSERT INTO[*] INFOEXECUTION (1,'test','test','test','2015-01-01','running')"; SQL statement:
SELECT * FROM INFOEXECUTION 
INSERT INTO INFOEXECUTION (1,'test','test','test','2015-01-01','running') [42000-190]
2017-06-20 14:17:14 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO INFOEXECUTION (1[*],'test','test','test','2015-01-01','running')"; expected "identifier"; SQL statement:
INSERT INTO INFOEXECUTION (1,'test','test','test','2015-01-01','running') [42001-190]
2017-06-20 14:17:26 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO INFOEXECUTION ('test'[*],'test','test','2015-01-01','running')"; expected "identifier"; SQL statement:
INSERT INTO INFOEXECUTION ('test','test','test','2015-01-01','running') [42001-190]
2017-06-20 14:17:27 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "INSERT INTO INFOEXECUTION ('test'[*],'test','test','2015-01-01','running')"; expected "identifier"; SQL statement:
INSERT INTO INFOEXECUTION ('test','test','test','2015-01-01','running') [42001-190]
2017-06-20 14:22:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-20 14:22:32 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-20 14:24:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-20 14:28:51 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-20 14:42:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-20 16:17:42 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-20 17:13:38 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-20 17:14:56 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-20 17:18:29 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-20 17:28:07 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-20 17:33:47 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-20 17:36:07 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-21 09:58:22 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-22 11:42:39 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-26 17:25:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-26 17:25:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-26 17:25:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-26 17:25:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-26 17:25:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-26 17:25:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-26 17:25:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-26 17:25:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-26 17:25:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-26 17:25:02 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-26 22:46:06 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-26 22:51:20 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-26 22:52:46 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-27 10:50:16 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-27 10:56:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-27 10:58:03 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-27 11:05:30 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-27 11:08:48 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-27 11:10:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-27 11:17:08 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-28 10:02:02 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-28 15:28:54 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-06-29 11:14:11 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-07-04 10:10:06 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-07-04 10:40:59 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-07-04 11:58:27 jdbc[4]: exception
org.h2.jdbc.JdbcSQLException: The object is already closed [90007-195]
2017-07-05 11:24:02 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]" [50000-195]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2476)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:55)
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:75)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:106)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:89)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:206)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:178)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.buildJdbcConnectionAccess(JdbcServicesImpl.java:260)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:94)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:89)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:206)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:178)
	at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.java:1885)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1843)
	at fr.insalyon.creatis.vip.cli.dao.HibernateUtil.init(HibernateUtil.java:19)
	at fr.insalyon.creatis.vip.cli.control.Controller.main(Controller.java:66)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]" [50000-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 36 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 31 more
2017-07-05 11:33:21 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]" [50000-195]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2476)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:55)
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:75)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:106)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:89)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:206)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:178)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.buildJdbcConnectionAccess(JdbcServicesImpl.java:260)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:94)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:89)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:206)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:178)
	at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.java:1885)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1843)
	at fr.insalyon.creatis.vip.cli.dao.HibernateUtil.init(HibernateUtil.java:19)
	at fr.insalyon.creatis.vip.cli.control.Controller.main(Controller.java:66)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]" [50000-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 36 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 31 more
2017-07-05 11:33:21 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]" [50000-195]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2476)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:55)
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:75)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:106)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:89)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:206)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:178)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.buildJdbcConnectionAccess(JdbcServicesImpl.java:260)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:94)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:89)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:206)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:178)
	at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.java:1885)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1843)
	at fr.insalyon.creatis.vip.cli.dao.HibernateUtil.init(HibernateUtil.java:19)
	at fr.insalyon.creatis.vip.cli.control.Controller.main(Controller.java:66)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]" [50000-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 36 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 31 more
2017-07-05 11:33:21 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]" [50000-195]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2476)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:55)
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:75)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:106)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:89)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:206)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:178)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.buildJdbcConnectionAccess(JdbcServicesImpl.java:260)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:94)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:89)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:206)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:178)
	at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.java:1885)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1843)
	at fr.insalyon.creatis.vip.cli.dao.HibernateUtil.init(HibernateUtil.java:19)
	at fr.insalyon.creatis.vip.cli.control.Controller.main(Controller.java:66)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]" [50000-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 36 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 31 more
2017-07-06 10:48:14 database: flush
org.h2.message.DbException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]" [50000-195]
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.mvstore.db.MVTableEngine$1.uncaughtException(MVTableEngine.java:95)
	at org.h2.mvstore.MVStore.panic(MVStore.java:378)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:361)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:155)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:100)
	at org.h2.engine.Database.getPageStore(Database.java:2476)
	at org.h2.engine.Database.open(Database.java:697)
	at org.h2.engine.Database.openDatabase(Database.java:276)
	at org.h2.engine.Database.<init>(Database.java:270)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:354)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:116)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:100)
	at org.h2.Driver.connect(Driver.java:69)
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:55)
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:75)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:106)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:89)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:206)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:178)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.buildJdbcConnectionAccess(JdbcServicesImpl.java:260)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:94)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:89)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:206)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:178)
	at org.hibernate.cfg.Configuration.buildTypeRegistrations(Configuration.java:1885)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1843)
	at fr.insalyon.creatis.vip.cli.dao.HibernateUtil.init(HibernateUtil.java:19)
	at fr.insalyon.creatis.vip.cli.control.Controller.main(Controller.java:76)
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]" [50000-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	... 36 more
Caused by: java.lang.IllegalStateException: The file is locked: nio:/Users/qifan/GitHub/vip_client/VipClientDb.mv.db [1.4.195/7]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:765)
	at org.h2.mvstore.FileStore.open(FileStore.java:173)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:347)
	... 31 more
